### ISSUE TITLE
Issue with f.cir iles containg subcircuits.

### ISSUE THREAD

**Issue by VSD-DACteam** [CharuGupta-eng/OS-power-analysis-tool#4]
Hi Charu,
My spice netlist contains subcircuits. The script is'nt working due to the same. Please look into it so that i can do power analysis for my circuit.
The  netlist is upload in the below mentioned github repository with the name "10bitdac.cir"
https://github.com/VSD-DACteam/avsddac_3v3
Thankyou

**Comment by CharuGupta-eng** [comment]
Hi
Sorry for inconvenience... I update my script now it works for your circuit also and you get average power. Can you please try once again....
Thanks
